import {
  LayoutDashboard, Database, Workflow, Compass, ShieldCheck, Sparkles,
  Scissors, GitFork, FunctionSquare, UserCog, Boxes, HeartPulse, Target,
  Network, Shuffle, Gauge, Package, Terminal, Play, Users, TrendingUp,
  Settings, MoreHorizontal, Layers, ListChecks, BadgeCheck, Lightbulb,
  Save, Code2, Lock, BookOpen, RefreshCw, Activity, Wrench, Search,
  Upload, Brain, Check, X, Clock, AlertTriangle, CheckCircle2, XCircle,
  ChevronDown, ChevronRight, ChevronLeft, ArrowLeft, RotateCcw, History,
  DollarSign, PanelLeftClose, PanelLeft, Snowflake,
  type LucideIcon,
} from 'lucide-react'

const ICON_MAP: Record<string, LucideIcon> = {
  LayoutDashboard,
  Database,
  Workflow,
  Compass,
  ShieldCheck,
  Sparkles,
  Scissors,
  GitFork,
  FunctionSquare,
  UserCog,
  Boxes,
  HeartPulse,
  Target,
  Network,
  Shuffle,
  Gauge,
  Package,
  Terminal,
  Play,
  Users,
  TrendingUp,
  Settings,
  MoreHorizontal,
  Layers,
  ListChecks,
  BadgeCheck,
  Lightbulb,
  Save,
  Code2,
  Lock,
  BookOpen,
  RefreshCw,
  Activity,
  Wrench,
  Search,
  Upload,
  Brain,
  Check,
  X,
  Clock,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ArrowLeft,
  RotateCcw,
  History,
  DollarSign,
  PanelLeftClose,
  PanelLeft,
  Snowflake,
}

export function DynamicIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICON_MAP[name] ?? LayoutDashboard
  return <Icon className={className} />
}
