#!/bin/bash
# SOTA Agentic OS — Production bootstrap script
#
# Fase 6.4 — Setup completo ambiente produzione
#
# Usage:
#   ./scripts/prod-bootstrap.sh [--with-redis]
#
# Questo script:
#   1. Verifica prerequisiti (docker, bun)
#   2. Avvia i servizi Docker (Postgres + NATS + Langfuse + opzionale Redis)
#   3. Attende che i servizi siano healthy
#   4. Crea il database Langfuse se non esiste
#   5. Switcha lo schema Prisma a PostgreSQL
#   6. Esegue db:push
#   7. Genera chiavi Langfuse e le stampa
#   8. Stampa un .env.production ready-to-use

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log() { echo -e "${GREEN}[bootstrap]${NC} $1"; }
warn() { echo -e "${YELLOW}[warn]${NC} $1"; }
error() { echo -e "${RED}[error]${NC} $1"; exit 1; }

# Check prerequisites
check_prereqs() {
  log "Checking prerequisites..."

  command -v docker >/dev/null 2>&1 || error "docker not found. Install: https://docs.docker.com/get-docker/"
  command -v bun >/dev/null 2>&1 || error "bun not found. Install: https://bun.sh/"

  docker info >/dev/null 2>&1 || error "docker daemon not running. Start it first."

  log "Prerequisites OK"
}

# Start Docker services
start_services() {
  log "Starting Docker services..."

  if [ "$1" = "--with-redis" ]; then
    docker compose --profile with-redis up -d
  else
    docker compose up -d
  fi

  log "Waiting for services to be healthy..."

  # Wait for postgres
  wait_for_healthy sota-postgres 60
  log "Postgres is healthy"

  # Wait for NATS
  wait_for_healthy sota-nats 30
  log "NATS is healthy"

  # Wait for Langfuse (takes longer)
  wait_for_healthy sota-langfuse 120
  log "Langfuse is healthy"

  if [ "$1" = "--with-redis" ]; then
    wait_for_healthy sota-redis 30
    log "Redis is healthy"
  fi
}

wait_for_healthy() {
  local container=$1
  local max_wait=$2
  local waited=0
  while [ $waited -lt $max_wait ]; do
    local status=$(docker inspect --format='{{.State.Health.Status}}' $container 2>/dev/null || echo "not found")
    if [ "$status" = "healthy" ]; then
      return 0
    fi
    echo -n "."
    sleep 2
    waited=$((waited + 2))
  done
  echo
  error "Timeout waiting for $container to be healthy (waited ${waited}s)"
}

# Create Langfuse database
create_langfuse_db() {
  log "Creating Langfuse database if not exists..."
  docker exec sota-postgres psql -U sota -d postgres -c "CREATE DATABASE langfuse;" 2>/dev/null || true
  log "Langfuse database ready"
}

# Switch Prisma schema to PostgreSQL
switch_schema() {
  log "Switching Prisma schema to PostgreSQL..."
  cp prisma/schema.prisma prisma/schema.sqlite.prisma.bak 2>/dev/null || true
  cp prisma/schema.postgres.prisma prisma/schema.prisma
  log "Schema switched (SQLite backup at prisma/schema.sqlite.prisma.bak)"
}

# Push schema to PostgreSQL
push_schema() {
  log "Pushing schema to PostgreSQL..."
  DATABASE_URL=postgresql://sota:sota@localhost:5432/sota bun run db:push
  log "Schema pushed"
}

# Generate .env.production
generate_env() {
  local env_file=".env.production"

  log "Generating $env_file..."

  # Generate random secrets
  local nextauth_secret=$(openssl rand -base64 32 2>/dev/null || echo "fallback-secret-change-me")
  local langfuse_salt=$(openssl rand -base64 32 2>/dev/null || echo "fallback-salt-change-me")

  cat > "$env_file" <<EOF
# SOTA Agentic OS — Production environment
# Generated by scripts/prod-bootstrap.sh on $(date)

# Database (AgensGraph: PostgreSQL + AGE + pgvector)
DATABASE_URL=postgresql://sota:sota@localhost:5432/sota

# Event Mesh (NATS JetStream)
NATS_URL=nats://localhost:4222

# Observability (Langfuse self-host)
LANGFUSE_URL=http://localhost:3001
LANGFUSE_PUBLIC_KEY=pk-lh-...
LANGFUSE_SECRET_KEY=sk-lh-...
LANGFUSE_NEXTAUTH_SECRET=$nextauth_secret
LANGFUSE_SALT=$langfuse_salt

# LLM (ZAI SDK)
ZAI_API_KEY=your-zai-api-key

# Optional: Redis (cache + alternative event mesh)
# REDIS_URL=redis://localhost:6379
EOF

  log "Generated $env_file"
  warn "Edit it to add your ZAI_API_KEY and Langfuse keys"
}

# Print next steps
print_next_steps() {
  echo
  echo -e "${GREEN}=== SOTA Agentic OS Production Setup Complete ===${NC}"
  echo
  echo "Services running:"
  echo "  - PostgreSQL (AgensGraph): localhost:5432"
  echo "  - NATS JetStream: localhost:4222 (monitoring: localhost:8222)"
  echo "  - Langfuse: http://localhost:3001"
  if [ "$1" = "--with-redis" ]; then
    echo "  - Redis: localhost:6379"
  fi
  echo
  echo "Next steps:"
  echo "  1. Open http://localhost:3001 to setup Langfuse (first run creates admin user)"
  echo "  2. In Langfuse, create a project and copy the public + secret keys"
  echo "  3. Edit .env.production with the Langfuse keys and your ZAI_API_KEY"
  echo "  4. Source the env file: export \$(cat .env.production | xargs)"
  echo "  5. Start the app: bun run dev"
  echo
  echo "To stop services: docker compose down"
  echo "To reset everything: docker compose down -v && rm -f .env.production"
}

# Main
main() {
  log "SOTA Agentic OS — Production bootstrap"
  echo

  check_prereqs
  start_services "$1"
  create_langfuse_db
  switch_schema
  push_schema
  generate_env
  print_next_steps "$1"
}

main "$@"
