'use client'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import { cn } from '@/lib/utils'
import { CheckCircle2, XCircle, AlertTriangle, Activity, ListChecks, Inbox } from 'lucide-react'
import { EmptyState } from '@/components/shared/empty-state'
import type { Narrative, LogEntry, SchedulerTask, CycleSnapshot, SteeringEvent, SafetyItem } from './types'

export function NarrativeTab({ narratives }: { narratives: Narrative[] }) {
 return <Card><CardHeader><CardTitle>Narrativa ad alto livello</CardTitle><CardDescription>Dialogo dell agente</CardDescription></CardHeader><CardContent><ScrollArea className="h-96 pr-2">{narratives.length === 0 ? <EmptyState icon={Activity} title="Nessuna narrativa" description="Le azioni appariranno qui." /> : <ul className="space-y-2">{narratives.map(n => <li key={n.id} className={cn('rounded-md border-l-2 bg-card shadow-sm p-3 hover:shadow-md transition-shadow', n.level === 'critical' && 'border-l-status-danger', n.level === 'warn' && 'border-l-status-warn', n.level === 'info' && 'border-l-status-info')}><div className="flex items-center gap-2 mb-1"><Badge variant="secondary" className="text-[10px] font-mono">{n.agentId}</Badge>{n.relatedPhase && <Badge variant="outline" className="text-[10px]">F{n.relatedPhase}</Badge>}{n.cycleId && <Badge variant="outline" className="text-[10px] font-mono">#{n.cycleId}</Badge>}<span className="text-[10px] text-muted-foreground ml-auto">{new Date(n.timestamp).toLocaleString('it-IT')}</span></div><div className="text-xs">{n.narrative}</div></li>)}</ul>}</ScrollArea></CardContent></Card>
}
export function LogTab({ logs }: { logs: LogEntry[] }) {
 return <Card><CardHeader><CardTitle>Traccia tecnica</CardTitle><CardDescription>{logs.length} eventi</CardDescription></CardHeader><CardContent><ScrollArea className="h-96 pr-2">{logs.length === 0 ? <EmptyState icon={Inbox} title="Nessun evento" /> : <ul className="space-y-0.5">{logs.map(l => <li key={l.id} className="text-xs flex items-center gap-2 py-1 px-2 hover:bg-muted/40 rounded-sm transition-colors"><Badge variant="outline" className={cn('text-[9px] font-mono shrink-0', l.level === 'warn' && 'border-status-warn/40 text-status-warn', l.level === 'error' && 'border-status-danger/40 text-status-danger')}>P{l.phase}</Badge><span className="text-muted-foreground font-mono shrink-0 text-[10px]">{l.agentId}</span><span className="font-mono text-[11px] truncate flex-1">{l.event}</span><span className="text-[10px] text-muted-foreground shrink-0">{new Date(l.timestamp).toLocaleTimeString('it-IT')}</span></li>)}</ul>}</ScrollArea></CardContent></Card>
}
export function SchedulerTab({ tasks }: { tasks: SchedulerTask[] }) {
 return <Card><CardHeader><CardTitle>Task in background</CardTitle><CardDescription>{tasks.length} task</CardDescription></CardHeader><CardContent><ScrollArea className="h-96 pr-2">{tasks.length === 0 ? <EmptyState icon={ListChecks} title="Nessun task" description="Genera un piano." /> : <ul className="space-y-2">{tasks.map(t => <li key={t.id} className="rounded-md border bg-card shadow-sm p-3 hover:shadow-md transition-shadow"><div className="flex items-center gap-2 mb-1"><Badge variant="outline" className="font-mono">{t.taskId}</Badge><Badge variant="secondary" className={cn('text-[10px]', t.status === 'done' && 'bg-status-ok/15 text-status-ok', t.status === 'running' && 'bg-status-info/15 text-status-info', t.status === 'failed' && 'bg-status-danger/15 text-status-danger', t.status === 'pending' && 'bg-muted')}>{t.status}</Badge><span className="text-[10px] text-muted-foreground font-mono">{t.agentId}</span></div><div className="text-[11px]">{t.description}</div><div className="text-[10px] text-muted-foreground mt-1 truncate">Piano: {t.plan?.taskGoal}</div></li>)}</ul>}</ScrollArea></CardContent></Card>
}
export function CyclesTab({ snapshots, steeringEvents }: { snapshots: CycleSnapshot[]; steeringEvents: SteeringEvent[] }) {
 return <div className="grid lg:grid-cols-2 gap-4"><Card><CardHeader><CardTitle>Cicli cognitivi</CardTitle><CardDescription>{snapshots.length} snapshot</CardDescription></CardHeader><CardContent><ScrollArea className="h-80 pr-2"><ul className="space-y-1.5">{snapshots.map(s => <li key={s.id} className="rounded-md border bg-card p-2 hover:bg-muted/30 transition-colors"><div className="flex items-center gap-2"><Badge variant="outline" className="font-mono">#{s.cycleId}</Badge><Badge variant="secondary">load {(s.systemLoad * 100).toFixed(0)}%</Badge><Badge variant="secondary">Q{s.queueDepth}</Badge><Badge variant="secondary">T{s.activeThreads}</Badge><span className="text-[10px] text-muted-foreground ml-auto">{new Date(s.timestamp).toLocaleTimeString('it-IT')}</span></div></li>)}</ul></ScrollArea></CardContent></Card><Card><CardHeader><CardTitle>Steering events</CardTitle><CardDescription>{steeringEvents.length} eventi ACTS</CardDescription></CardHeader><CardContent><ScrollArea className="h-80 pr-2"><ul className="space-y-1.5">{steeringEvents.map(e => <li key={e.id} className="rounded-md border bg-card p-2 hover:bg-muted/30 transition-colors"><div className="flex items-center gap-2"><Badge variant="outline" className="font-mono">{e.strategy}</Badge><Badge variant="secondary">{e.tokenUsed} tok</Badge><span className="text-[10px] text-muted-foreground ml-auto">{new Date(e.timestamp).toLocaleTimeString('it-IT')}</span></div></li>)}</ul></ScrollArea></CardContent></Card></div>
}
export function SafetyTab({ safetyItems }: { safetyItems: SafetyItem[] }) {
 return <Card><CardHeader><CardTitle className="flex items-center gap-2"><AlertTriangle className="size-4 text-status-warn" />Azioni bloccate</CardTitle><CardDescription>Risolvi come Sovereign Validator</CardDescription></CardHeader><CardContent><ScrollArea className="h-96 pr-2">{safetyItems.length === 0 ? <div className="flex flex-col items-center justify-center py-8"><CheckCircle2 className="size-12 text-status-ok mb-2" /><p className="text-sm font-medium text-muted-foreground">Nessuna azione bloccata</p><p className="text-xs text-muted-foreground/70">Il sistema è in salute.</p></div> : <ul className="space-y-2">{safetyItems.map(s => <li key={s.id} className="rounded-md border border-status-warn/30 bg-status-warn/5 p-3 hover:shadow-md transition-shadow"><div className="flex items-center gap-2 mb-2"><XCircle className="size-4 text-status-warn" /><Badge variant="outline" className="font-mono">{s.source}</Badge><Badge variant="warning">{s.status}</Badge><span className="text-[10px] text-muted-foreground ml-auto">{new Date(s.createdAt).toLocaleString('it-IT')}</span></div><div className="text-xs font-medium mb-1">Azione: "{s.action}"</div><pre className="text-[11px] text-muted-foreground whitespace-pre-wrap bg-muted/30 rounded-md p-2">{s.readableExplanation}</pre></li>)}</ul>}</ScrollArea></CardContent></Card>
}
